# Favicon
favicon: /favicon.ico

# SEO
keywords: 生活,博客

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  GitHub: https://github.com/afox666

# Nav menu
menu:
  Home: /
  Archives: /archives
  About: /about